//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 5.0.61118.0
// 
namespace AndroidApplication
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/AndroidApplication")]
    public partial class Account : object
    {
        
        private int AccountidField;
        
        private string EmailField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Accountid
        {
            get
            {
                return this.AccountidField;
            }
            set
            {
                this.AccountidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HelloWorldData", Namespace="http://schemas.datacontract.org/2004/07/AndroidApplication")]
    public partial class HelloWorldData : object
    {
        
        private string NameField;
        
        private bool SayHelloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SayHello
        {
            get
            {
                return this.SayHelloField;
            }
            set
            {
                this.SayHelloField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IAndroidApplicationService")]
public interface IAndroidApplicationService
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAndroidApplicationService/Authenticate", ReplyAction="http://tempuri.org/IAndroidApplicationService/AuthenticateResponse")]
    System.IAsyncResult BeginAuthenticate(string email, string password, System.AsyncCallback callback, object asyncState);
    
    bool EndAuthenticate(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAndroidApplicationService/GetAccount", ReplyAction="http://tempuri.org/IAndroidApplicationService/GetAccountResponse")]
    System.IAsyncResult BeginGetAccount(string email, string password, System.AsyncCallback callback, object asyncState);
    
    AndroidApplication.Account EndGetAccount(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAndroidApplicationService/SayHelloTo", ReplyAction="http://tempuri.org/IAndroidApplicationService/SayHelloToResponse")]
    System.IAsyncResult BeginSayHelloTo(string name, System.AsyncCallback callback, object asyncState);
    
    string EndSayHelloTo(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAndroidApplicationService/GetHelloData", ReplyAction="http://tempuri.org/IAndroidApplicationService/GetHelloDataResponse")]
    System.IAsyncResult BeginGetHelloData(AndroidApplication.HelloWorldData helloWorldData, System.AsyncCallback callback, object asyncState);
    
    AndroidApplication.HelloWorldData EndGetHelloData(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAndroidApplicationServiceChannel : IAndroidApplicationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public AndroidApplication.Account Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((AndroidApplication.Account)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SayHelloToCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public SayHelloToCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class GetHelloDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public GetHelloDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public AndroidApplication.HelloWorldData Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((AndroidApplication.HelloWorldData)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AndroidApplicationServiceClient : System.ServiceModel.ClientBase<IAndroidApplicationService>, IAndroidApplicationService
{
    
    private BeginOperationDelegate onBeginAuthenticateDelegate;
    
    private EndOperationDelegate onEndAuthenticateDelegate;
    
    private System.Threading.SendOrPostCallback onAuthenticateCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetAccountDelegate;
    
    private EndOperationDelegate onEndGetAccountDelegate;
    
    private System.Threading.SendOrPostCallback onGetAccountCompletedDelegate;
    
    private BeginOperationDelegate onBeginSayHelloToDelegate;
    
    private EndOperationDelegate onEndSayHelloToDelegate;
    
    private System.Threading.SendOrPostCallback onSayHelloToCompletedDelegate;
    
    private BeginOperationDelegate onBeginGetHelloDataDelegate;
    
    private EndOperationDelegate onEndGetHelloDataDelegate;
    
    private System.Threading.SendOrPostCallback onGetHelloDataCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public AndroidApplicationServiceClient()
    {
    }
    
    public AndroidApplicationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AndroidApplicationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AndroidApplicationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AndroidApplicationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<AuthenticateCompletedEventArgs> AuthenticateCompleted;
    
    public event System.EventHandler<GetAccountCompletedEventArgs> GetAccountCompleted;
    
    public event System.EventHandler<SayHelloToCompletedEventArgs> SayHelloToCompleted;
    
    public event System.EventHandler<GetHelloDataCompletedEventArgs> GetHelloDataCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAndroidApplicationService.BeginAuthenticate(string email, string password, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginAuthenticate(email, password, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool IAndroidApplicationService.EndAuthenticate(System.IAsyncResult result)
    {
        return base.Channel.EndAuthenticate(result);
    }
    
    private System.IAsyncResult OnBeginAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string email = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        return ((IAndroidApplicationService)(this)).BeginAuthenticate(email, password, callback, asyncState);
    }
    
    private object[] OnEndAuthenticate(System.IAsyncResult result)
    {
        bool retVal = ((IAndroidApplicationService)(this)).EndAuthenticate(result);
        return new object[] {
                retVal};
    }
    
    private void OnAuthenticateCompleted(object state)
    {
        if ((this.AuthenticateCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void AuthenticateAsync(string email, string password)
    {
        this.AuthenticateAsync(email, password, null);
    }
    
    public void AuthenticateAsync(string email, string password, object userState)
    {
        if ((this.onBeginAuthenticateDelegate == null))
        {
            this.onBeginAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginAuthenticate);
        }
        if ((this.onEndAuthenticateDelegate == null))
        {
            this.onEndAuthenticateDelegate = new EndOperationDelegate(this.OnEndAuthenticate);
        }
        if ((this.onAuthenticateCompletedDelegate == null))
        {
            this.onAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateCompleted);
        }
        base.InvokeAsync(this.onBeginAuthenticateDelegate, new object[] {
                    email,
                    password}, this.onEndAuthenticateDelegate, this.onAuthenticateCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAndroidApplicationService.BeginGetAccount(string email, string password, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetAccount(email, password, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AndroidApplication.Account IAndroidApplicationService.EndGetAccount(System.IAsyncResult result)
    {
        return base.Channel.EndGetAccount(result);
    }
    
    private System.IAsyncResult OnBeginGetAccount(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string email = ((string)(inValues[0]));
        string password = ((string)(inValues[1]));
        return ((IAndroidApplicationService)(this)).BeginGetAccount(email, password, callback, asyncState);
    }
    
    private object[] OnEndGetAccount(System.IAsyncResult result)
    {
        AndroidApplication.Account retVal = ((IAndroidApplicationService)(this)).EndGetAccount(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetAccountCompleted(object state)
    {
        if ((this.GetAccountCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetAccountCompleted(this, new GetAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetAccountAsync(string email, string password)
    {
        this.GetAccountAsync(email, password, null);
    }
    
    public void GetAccountAsync(string email, string password, object userState)
    {
        if ((this.onBeginGetAccountDelegate == null))
        {
            this.onBeginGetAccountDelegate = new BeginOperationDelegate(this.OnBeginGetAccount);
        }
        if ((this.onEndGetAccountDelegate == null))
        {
            this.onEndGetAccountDelegate = new EndOperationDelegate(this.OnEndGetAccount);
        }
        if ((this.onGetAccountCompletedDelegate == null))
        {
            this.onGetAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAccountCompleted);
        }
        base.InvokeAsync(this.onBeginGetAccountDelegate, new object[] {
                    email,
                    password}, this.onEndGetAccountDelegate, this.onGetAccountCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAndroidApplicationService.BeginSayHelloTo(string name, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSayHelloTo(name, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    string IAndroidApplicationService.EndSayHelloTo(System.IAsyncResult result)
    {
        return base.Channel.EndSayHelloTo(result);
    }
    
    private System.IAsyncResult OnBeginSayHelloTo(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string name = ((string)(inValues[0]));
        return ((IAndroidApplicationService)(this)).BeginSayHelloTo(name, callback, asyncState);
    }
    
    private object[] OnEndSayHelloTo(System.IAsyncResult result)
    {
        string retVal = ((IAndroidApplicationService)(this)).EndSayHelloTo(result);
        return new object[] {
                retVal};
    }
    
    private void OnSayHelloToCompleted(object state)
    {
        if ((this.SayHelloToCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.SayHelloToCompleted(this, new SayHelloToCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void SayHelloToAsync(string name)
    {
        this.SayHelloToAsync(name, null);
    }
    
    public void SayHelloToAsync(string name, object userState)
    {
        if ((this.onBeginSayHelloToDelegate == null))
        {
            this.onBeginSayHelloToDelegate = new BeginOperationDelegate(this.OnBeginSayHelloTo);
        }
        if ((this.onEndSayHelloToDelegate == null))
        {
            this.onEndSayHelloToDelegate = new EndOperationDelegate(this.OnEndSayHelloTo);
        }
        if ((this.onSayHelloToCompletedDelegate == null))
        {
            this.onSayHelloToCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSayHelloToCompleted);
        }
        base.InvokeAsync(this.onBeginSayHelloToDelegate, new object[] {
                    name}, this.onEndSayHelloToDelegate, this.onSayHelloToCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IAndroidApplicationService.BeginGetHelloData(AndroidApplication.HelloWorldData helloWorldData, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetHelloData(helloWorldData, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AndroidApplication.HelloWorldData IAndroidApplicationService.EndGetHelloData(System.IAsyncResult result)
    {
        return base.Channel.EndGetHelloData(result);
    }
    
    private System.IAsyncResult OnBeginGetHelloData(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        AndroidApplication.HelloWorldData helloWorldData = ((AndroidApplication.HelloWorldData)(inValues[0]));
        return ((IAndroidApplicationService)(this)).BeginGetHelloData(helloWorldData, callback, asyncState);
    }
    
    private object[] OnEndGetHelloData(System.IAsyncResult result)
    {
        AndroidApplication.HelloWorldData retVal = ((IAndroidApplicationService)(this)).EndGetHelloData(result);
        return new object[] {
                retVal};
    }
    
    private void OnGetHelloDataCompleted(object state)
    {
        if ((this.GetHelloDataCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.GetHelloDataCompleted(this, new GetHelloDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void GetHelloDataAsync(AndroidApplication.HelloWorldData helloWorldData)
    {
        this.GetHelloDataAsync(helloWorldData, null);
    }
    
    public void GetHelloDataAsync(AndroidApplication.HelloWorldData helloWorldData, object userState)
    {
        if ((this.onBeginGetHelloDataDelegate == null))
        {
            this.onBeginGetHelloDataDelegate = new BeginOperationDelegate(this.OnBeginGetHelloData);
        }
        if ((this.onEndGetHelloDataDelegate == null))
        {
            this.onEndGetHelloDataDelegate = new EndOperationDelegate(this.OnEndGetHelloData);
        }
        if ((this.onGetHelloDataCompletedDelegate == null))
        {
            this.onGetHelloDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetHelloDataCompleted);
        }
        base.InvokeAsync(this.onBeginGetHelloDataDelegate, new object[] {
                    helloWorldData}, this.onEndGetHelloDataDelegate, this.onGetHelloDataCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override IAndroidApplicationService CreateChannel()
    {
        return new AndroidApplicationServiceClientChannel(this);
    }
    
    private class AndroidApplicationServiceClientChannel : ChannelBase<IAndroidApplicationService>, IAndroidApplicationService
    {
        
        public AndroidApplicationServiceClientChannel(System.ServiceModel.ClientBase<IAndroidApplicationService> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginAuthenticate(string email, string password, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = email;
            _args[1] = password;
            System.IAsyncResult _result = base.BeginInvoke("Authenticate", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndAuthenticate(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("Authenticate", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetAccount(string email, string password, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = email;
            _args[1] = password;
            System.IAsyncResult _result = base.BeginInvoke("GetAccount", _args, callback, asyncState);
            return _result;
        }
        
        public AndroidApplication.Account EndGetAccount(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            AndroidApplication.Account _result = ((AndroidApplication.Account)(base.EndInvoke("GetAccount", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginSayHelloTo(string name, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = name;
            System.IAsyncResult _result = base.BeginInvoke("SayHelloTo", _args, callback, asyncState);
            return _result;
        }
        
        public string EndSayHelloTo(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            string _result = ((string)(base.EndInvoke("SayHelloTo", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginGetHelloData(AndroidApplication.HelloWorldData helloWorldData, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = helloWorldData;
            System.IAsyncResult _result = base.BeginInvoke("GetHelloData", _args, callback, asyncState);
            return _result;
        }
        
        public AndroidApplication.HelloWorldData EndGetHelloData(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            AndroidApplication.HelloWorldData _result = ((AndroidApplication.HelloWorldData)(base.EndInvoke("GetHelloData", _args, result)));
            return _result;
        }
    }
}
